import { Knex } from "knex"

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("actors").del()

    // Inserts seed entries
    await knex("actors").insert([
        {
            first_name: "Malin",
            last_name: "Akerman",
            gender: "F",
            date_of_birth: "1978-05-12",
        },
        {
            first_name: "Tim",
            last_name: "Allen",
            gender: "M",
            date_of_birth: "1953-06-13",
        },
        {
            first_name: "Julie",
            last_name: "Andrews",
            gender: "F",
            date_of_birth: "1935-10-01",
        },
        {
            first_name: "Ivana",
            last_name: "Baquero",
            gender: "F",
            date_of_birth: "1994-06-11",
        },
        {
            first_name: "Lorraine",
            last_name: "Bracco",
            gender: "F",
            date_of_birth: "1954-10-02",
        },
        {
            first_name: "Alice",
            last_name: "Braga",
            gender: "F",
            date_of_birth: "1983-04-15",
        },
        {
            first_name: "Marlon",
            last_name: "Brando",
            gender: "M",
            date_of_birth: "1924-04-03",
        },
        {
            first_name: "Adrien",
            last_name: "Brody",
            gender: "M",
            date_of_birth: "1973-04-14",
        },
        {
            first_name: "Peter",
            last_name: "Carlberg",
            gender: "M",
            date_of_birth: "1950-12-08",
        },
        {
            first_name: "Gemma",
            last_name: "Chan",
            gender: "F",
            date_of_birth: "1982-11-29",
        },
        {
            first_name: "Chen",
            last_name: "Chang",
            gender: "M",
            date_of_birth: "1976-10-14",
        },
        {
            first_name: "Graham",
            last_name: "Chapman",
            gender: "M",
            date_of_birth: "1941-01-08",
        },
        {
            first_name: "Pei-pei",
            last_name: "Cheng",
            gender: "F",
            date_of_birth: "1946-12-04",
        },
        {
            first_name: "Maggie ",
            last_name: "Cheung",
            gender: "F",
            date_of_birth: "1964-09-20",
        },
        {
            first_name: "Min-sik",
            last_name: "Choi",
            gender: "M",
            date_of_birth: "1962-05-30",
        },
        {
            first_name: "Yun-fat",
            last_name: "Chow",
            gender: "M",
            date_of_birth: "1955-05-18",
        },
        {
            first_name: "John",
            last_name: "Cleese",
            gender: "M",
            date_of_birth: "1939-10-27",
        },
        {
            first_name: "Paddy",
            last_name: "Considine",
            gender: "M",
            date_of_birth: "1973-09-05",
        },
        {
            first_name: "Abbie",
            last_name: "Cornish",
            gender: "F",
            date_of_birth: "1982-08-07",
        },
        {
            first_name: "Brian",
            last_name: "Cox",
            gender: "M",
            date_of_birth: "1946-06-01",
        },
        {
            first_name: "Scatman",
            last_name: "Crothers",
            gender: "M",
            date_of_birth: "1910-05-23",
        },
        {
            first_name: "Russell",
            last_name: "Crowe",
            gender: "M",
            date_of_birth: "1964-04-07",
        },
        {
            first_name: "Tom",
            last_name: "Cruise",
            gender: "M",
            date_of_birth: "1962-07-03",
        },
        {
            first_name: "Darlan",
            last_name: "Cunha",
            gender: "M",
            date_of_birth: "1988-07-26",
        },
        {
            first_name: "Willem",
            last_name: "Dafoe",
            gender: "M",
            date_of_birth: "1955-07-22",
        },
        {
            first_name: "Paul",
            last_name: "Dano",
            gender: "M",
            date_of_birth: "1984-06-19",
        },
        {
            first_name: "Daniel",
            last_name: "Day-Lewis",
            gender: "M",
            date_of_birth: "1957-04-29",
        },
        {
            first_name: "Robert",
            last_name: "De Niro",
            gender: "M",
            date_of_birth: "1943-08-17",
        },
        {
            first_name: "unknown",
            last_name: "Denden",
            gender: "M",
            date_of_birth: "1950-01-23",
        },
        {
            first_name: "Leonardo",
            last_name: "DiCaprio",
            gender: "M",
            date_of_birth: "1974-11-11",
        },
        {
            first_name: "Peter",
            last_name: "Dinklage",
            gender: "M",
            date_of_birth: "1969-06-11",
        },
        {
            first_name: "Hiroki",
            last_name: "Doi",
            gender: "M",
            date_of_birth: "1999-08-10",
        },
        {
            first_name: "Kirsten",
            last_name: "Dunst",
            gender: "F",
            date_of_birth: "1982-04-30",
        },
        {
            first_name: "Shelley",
            last_name: "Duvall",
            gender: "F",
            date_of_birth: "1949-07-07",
        },
        {
            first_name: "Ralph",
            last_name: "Fiennes",
            gender: "M",
            date_of_birth: "1962-12-22",
        },
        {
            first_name: "Leandro",
            last_name: "Firmino",
            gender: "M",
            date_of_birth: "1978-06-23",
        },
        {
            first_name: "Carrie",
            last_name: "Fisher",
            gender: "F",
            date_of_birth: "1956-10-21",
        },
        {
            first_name: "Harrison",
            last_name: "Ford",
            gender: "M",
            date_of_birth: "1942-07-13",
        },
        {
            first_name: "Jodie",
            last_name: "Foster",
            gender: "F",
            date_of_birth: "1962-11-19",
        },
        {
            first_name: "James",
            last_name: "Franco",
            gender: "M",
            date_of_birth: "1978-04-19",
        },
        {
            first_name: "Dillon",
            last_name: "Freasier",
            gender: "M",
            date_of_birth: "1996-03-06",
        },
        {
            first_name: "Tatsuya",
            last_name: "Fujiwara",
            gender: "M",
            date_of_birth: "1982-05-15",
        },
        {
            first_name: "Mitsuru",
            last_name: "Fukikoshi",
            gender: "M",
            date_of_birth: "1965-02-17",
        },
        {
            first_name: "Clark",
            last_name: "Gable",
            gender: "M",
            date_of_birth: "1901-02-01",
        },
        {
            first_name: "Mason",
            last_name: "Gamble",
            gender: "M",
            date_of_birth: "1986-01-16",
        },
        {
            first_name: "Xian",
            last_name: "Gao",
            gender: "M",
            date_of_birth: null,
        },
        {
            first_name: "Andrew",
            last_name: "Garfield",
            gender: "M",
            date_of_birth: "1983-08-20",
        },
        {
            first_name: "Judy",
            last_name: "Garland",
            gender: "F",
            date_of_birth: "1922-06-10",
        },
        {
            first_name: "Martina",
            last_name: "Gedeck",
            gender: "F",
            date_of_birth: "1961-09-14",
        },
        {
            first_name: "Jeff",
            last_name: "Goldblum",
            gender: "M",
            date_of_birth: "1952-10-22",
        },
        {
            first_name: "Carla",
            last_name: "Gugino",
            gender: "F",
            date_of_birth: "1971-08-29",
        },
        {
            first_name: "Alec",
            last_name: "Guiness",
            gender: "M",
            date_of_birth: "1914-04-02",
        },
        {
            first_name: "Jackey",
            last_name: "Haley",
            gender: "M",
            date_of_birth: "1961-07-14",
        },
        {
            first_name: "Mark",
            last_name: "Hamill",
            gender: "M",
            date_of_birth: "1951-09-25",
        },
        {
            first_name: "Tom",
            last_name: "Hanks",
            gender: "M",
            date_of_birth: "1956-07-09",
        },
        {
            first_name: "Daryl",
            last_name: "Hannah",
            gender: "F",
            date_of_birth: "1958-12-03",
        },
        {
            first_name: "Woody",
            last_name: "Harrelson",
            gender: "M",
            date_of_birth: "1961-07-23",
        },
        {
            first_name: "Rutger",
            last_name: "Hauer",
            gender: "M",
            date_of_birth: "1944-01-23",
        },
        {
            first_name: "Sally",
            last_name: "Hawkins",
            gender: "F",
            date_of_birth: "1976-04-27",
        },
        {
            first_name: "Kare",
            last_name: "Hedebrant",
            gender: "M",
            date_of_birth: "1995-06-28",
        },
        {
            first_name: "Rumi",
            last_name: "Hiiragi",
            gender: "F",
            date_of_birth: "1987-08-01",
        },
        {
            first_name: "Ian",
            last_name: "Holm",
            gender: "M",
            date_of_birth: "1931-09-12",
        },
        {
            first_name: "Dennis",
            last_name: "Hopper",
            gender: "M",
            date_of_birth: "1936-05-17",
        },
        {
            first_name: "Eric",
            last_name: "Idle",
            gender: "M",
            date_of_birth: "1943-03-29",
        },
        {
            first_name: "Miyu",
            last_name: "Irino",
            gender: "M",
            date_of_birth: "1988-02-19",
        },
        {
            first_name: "Samuel",
            last_name: "Jackson",
            gender: "M",
            date_of_birth: "1948-12-21",
        },
        {
            first_name: "Terry",
            last_name: "Jones",
            gender: "M",
            date_of_birth: "1942-02-01",
        },
        {
            first_name: "Milla",
            last_name: "Jovovich",
            gender: "F",
            date_of_birth: "1975-12-17",
        },
        {
            first_name: "Megumi",
            last_name: "Kagurazaka",
            gender: "F",
            date_of_birth: "1981-09-28",
        },
        {
            first_name: "Takeshi",
            last_name: "Kaneshiro",
            gender: "M",
            date_of_birth: "1973-10-11",
        },
        {
            first_name: "Hei-Jung",
            last_name: "Kang",
            gender: "F",
            date_of_birth: "1982-01-04",
        },
        {
            first_name: "Irfan",
            last_name: "Khan",
            gender: "M",
            date_of_birth: "1967-01-07",
        },
        {
            first_name: "Nicole",
            last_name: "Kidman",
            gender: "F",
            date_of_birth: "1967-06-20",
        },
        {
            first_name: "Val",
            last_name: "Kilmer",
            gender: "M",
            date_of_birth: "1959-12-31",
        },
        {
            first_name: "Takeshi",
            last_name: "Kitano",
            gender: "M",
            date_of_birth: "1947-01-18",
        },
        {
            first_name: "Keira",
            last_name: "Knightley",
            gender: "F",
            date_of_birth: "1985-03-26",
        },
        {
            first_name: "Sebastian",
            last_name: "Koch",
            gender: "M",
            date_of_birth: "1962-05-31",
        },
        {
            first_name: "Asuka",
            last_name: "Kurosawa",
            gender: "F",
            date_of_birth: "1971-12-22",
        },
        {
            first_name: "Andy",
            last_name: "Lau",
            gender: "M",
            date_of_birth: "1961-09-27",
        },
        {
            first_name: "Jude",
            last_name: "Law",
            gender: "M",
            date_of_birth: "1972-12-29",
        },
        {
            first_name: "Lina",
            last_name: "Leandersson",
            gender: "F",
            date_of_birth: "1995-09-27",
        },
        {
            first_name: "Bruce",
            last_name: "Lee",
            gender: "M",
            date_of_birth: "1940-11-27",
        },
        {
            first_name: "Vivien",
            last_name: "Leigh",
            gender: "F",
            date_of_birth: "1913-11-05",
        },
        {
            first_name: "Tony",
            last_name: "Leung",
            gender: "M",
            date_of_birth: "1962-06-27",
        },
        {
            first_name: "Ray",
            last_name: "Liotta",
            gender: "M",
            date_of_birth: "1954-12-18",
        },
        {
            first_name: "Danny",
            last_name: "Lloyd",
            gender: "M",
            date_of_birth: "1972-10-13",
        },
        {
            first_name: "Sihung",
            last_name: "Lung",
            gender: "M",
            date_of_birth: "1930-01-01",
        },
        {
            first_name: "Aki",
            last_name: "Maeda",
            gender: "F",
            date_of_birth: "1985-07-11",
        },
        {
            first_name: "Tobey",
            last_name: "Maguire",
            gender: "M",
            date_of_birth: "1975-06-27",
        },
        {
            first_name: "Francis",
            last_name: "McDormand",
            gender: "F",
            date_of_birth: "1957-06-23",
        },
        {
            first_name: "Malcolm",
            last_name: "McDowell",
            gender: "M",
            date_of_birth: "1943-06-13",
        },
        {
            first_name: "Alfred",
            last_name: "Molina",
            gender: "M",
            date_of_birth: "1953-05-24",
        },
        {
            first_name: "Cathy",
            last_name: "Moriarty",
            gender: "F",
            date_of_birth: "1960-11-29",
        },
        {
            first_name: "Ulrich",
            last_name: "Muhe",
            gender: "M",
            date_of_birth: "1953-06-20",
        },
        {
            first_name: "Carey",
            last_name: "Mulligan",
            gender: "F",
            date_of_birth: "1985-05-28",
        },
        {
            first_name: "Bill",
            last_name: "Murray",
            gender: "M",
            date_of_birth: "1950-09-21",
        },
        {
            first_name: "Mari",
            last_name: "Natsuki",
            gender: "F",
            date_of_birth: "1952-05-02",
        },
        {
            first_name: "Jack",
            last_name: "Nicholson",
            gender: "M",
            date_of_birth: "1937-04-22",
        },
        {
            first_name: "Connie",
            last_name: "Nielsen",
            gender: "F",
            date_of_birth: "1965-07-03",
        },
        {
            first_name: "Ika",
            last_name: "Nord",
            gender: "F",
            date_of_birth: "1960-04-29",
        },
        {
            first_name: "Chuck",
            last_name: "Norris",
            gender: "M",
            date_of_birth: "1940-03-10",
        },
        {
            first_name: "Edward",
            last_name: "Norton",
            gender: "M",
            date_of_birth: "1969-08-18",
        },
        {
            first_name: "Gary",
            last_name: "Oldman",
            gender: "M",
            date_of_birth: "1958-03-21",
        },
        {
            first_name: "Yasmin",
            last_name: "Paige",
            gender: "F",
            date_of_birth: "1991-06-24",
        },
        {
            first_name: "Michael",
            last_name: "Palin",
            gender: "M",
            date_of_birth: "1943-05-05",
        },
        {
            first_name: "Rebecca",
            last_name: "Pan",
            gender: "F",
            date_of_birth: "1931-12-29",
        },
        {
            first_name: "Joe",
            last_name: "Pesci",
            gender: "M",
            date_of_birth: "1943-02-09",
        },
        {
            first_name: "Joaquin",
            last_name: "Phoenix",
            gender: "M",
            date_of_birth: "1974-10-28",
        },
        {
            first_name: "Natilie",
            last_name: "Portman",
            gender: "F",
            date_of_birth: "1981-06-09",
        },
        {
            first_name: "Per",
            last_name: "Ragnar",
            gender: "M",
            date_of_birth: "1941-05-29",
        },
        {
            first_name: "Oliver",
            last_name: "Reed",
            gender: "M",
            date_of_birth: "1938-02-13",
        },
        {
            first_name: "Jean",
            last_name: "Reno",
            gender: "M",
            date_of_birth: "1948-07-30",
        },
        {
            first_name: "Tony",
            last_name: "Revolori",
            gender: "M",
            date_of_birth: "1996-04-28",
        },
        {
            first_name: "Craig",
            last_name: "Roberts",
            gender: "M",
            date_of_birth: "1991-01-21",
        },
        {
            first_name: "Sam",
            last_name: "Rockwell",
            gender: "M",
            date_of_birth: "1968-11-05",
        },
        {
            first_name: "Alexandre",
            last_name: "Rodrigues",
            gender: "M",
            date_of_birth: "1983-05-21",
        },
        {
            first_name: "Saoirse",
            last_name: "Ronan",
            gender: "F",
            date_of_birth: "1994-04-12",
        },
        {
            first_name: "Roy",
            last_name: "Scheider",
            gender: "M",
            date_of_birth: "1932-11-10",
        },
        {
            first_name: "Jason",
            last_name: "Schwartzmann",
            gender: "M",
            date_of_birth: "1980-06-26",
        },
        {
            first_name: "Suraj",
            last_name: "Sharma",
            gender: "M",
            date_of_birth: "1993-03-21",
        },
        {
            first_name: "Martin",
            last_name: "Sheen",
            gender: "M",
            date_of_birth: "1940-08-03",
        },
        {
            first_name: "Douglas",
            last_name: "Silva",
            gender: "M",
            date_of_birth: "1988-09-27",
        },
        {
            first_name: "Dandan",
            last_name: "Song",
            gender: "F",
            date_of_birth: "1961-08-25",
        },
        {
            first_name: "Rafe",
            last_name: "Spall",
            gender: "M",
            date_of_birth: "1983-03-10",
        },
        {
            first_name: "Tilda",
            last_name: "Swinton",
            gender: "F",
            date_of_birth: "1960-11-05",
        },
        {
            first_name: "George",
            last_name: "Tokoro",
            gender: "M",
            date_of_birth: "1955-01-26",
        },
        {
            first_name: "Noah",
            last_name: "Taylor",
            gender: "M",
            date_of_birth: "1969-09-04",
        },
        {
            first_name: "Uma",
            last_name: "Thurman",
            gender: "F",
            date_of_birth: "1970-04-29",
        },
        {
            first_name: "John",
            last_name: "Travolta",
            gender: "M",
            date_of_birth: "1954-02-18",
        },
        {
            first_name: "Chris",
            last_name: "Tucker",
            gender: "M",
            date_of_birth: "1971-08-31",
        },
        {
            first_name: "Dick",
            last_name: "Van Dyke",
            gender: "M",
            date_of_birth: "1925-12-13",
        },
        {
            first_name: "Hugo",
            last_name: "Weaving",
            gender: "M",
            date_of_birth: "1960-04-04",
        },
        {
            first_name: "Olivia",
            last_name: "Williams",
            gender: "F",
            date_of_birth: "1968-07-26",
        },
        {
            first_name: "Mykelti",
            last_name: "Williamson",
            gender: "M",
            date_of_birth: "1957-03-04",
        },
        {
            first_name: "Bruce",
            last_name: "Willis",
            gender: "M",
            date_of_birth: "1955-03-19",
        },
        {
            first_name: "Luke",
            last_name: "Wilson",
            gender: "M",
            date_of_birth: "1971-09-21",
        },
        {
            first_name: "Owen",
            last_name: "Wilson",
            gender: "M",
            date_of_birth: "1968-11-18",
        },
        {
            first_name: "Patrick",
            last_name: "Wilson",
            gender: "M",
            date_of_birth: "1973-07-03",
        },
        {
            first_name: "Kate",
            last_name: "Winslet",
            gender: "F",
            date_of_birth: "1975-10-05",
        },
        {
            first_name: "Faye",
            last_name: "Wong",
            gender: "F",
            date_of_birth: "1969-08-08",
        },
        {
            first_name: "Robin",
            last_name: "Wright",
            gender: "F",
            date_of_birth: "1966-04-08",
        },
        {
            first_name: "Michelle",
            last_name: "Yeoh",
            gender: "F",
            date_of_birth: "1962-08-06",
        },
        {
            first_name: "Ji-tae",
            last_name: "Yoo",
            gender: "M",
            date_of_birth: "1976-04-13",
        },
        {
            first_name: "Jin-seo",
            last_name: "Yoon",
            gender: "F",
            date_of_birth: "1983-08-05",
        },
        {
            first_name: "Sean",
            last_name: "Young",
            gender: "F",
            date_of_birth: "1959-11-20",
        },
        {
            first_name: "Billy",
            last_name: "Zane",
            gender: "M",
            date_of_birth: "1966-02-24",
        },
        {
            first_name: "Ziyi",
            last_name: "Zhang",
            gender: "F",
            date_of_birth: "1979-02-09",
        },
    ])
}
