import { Knex } from "knex"

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("movies").del()

    // Inserts seed entries
    await knex("movies").insert([
        {
            movie_name: "A Clockwork Orange",
            movie_length: "112",
            movie_lang: "English",
            release_date: "1972-02-02",
            age_certificate: "18",
            director_id: "13",
        },
        {
            movie_name: "Apocalypse Now",
            movie_length: "168",
            movie_lang: "English",
            release_date: "1979-08-15",
            age_certificate: "15",
            director_id: "9",
        },
        {
            movie_name: "Battle Royale ",
            movie_length: "111",
            movie_lang: "Japanese",
            release_date: "2001-01-04",
            age_certificate: "18",
            director_id: "10",
        },
        {
            movie_name: "Blade Runner ",
            movie_length: "121",
            movie_lang: "English",
            release_date: "1982-06-25",
            age_certificate: "15",
            director_id: "27",
        },
        {
            movie_name: "Chungking Express",
            movie_length: "113",
            movie_lang: "Chinese",
            release_date: "1996-08-03",
            age_certificate: "15",
            director_id: "35",
        },
        {
            movie_name: "City of God",
            movie_length: "145",
            movie_lang: "Portuguese",
            release_date: "2003-01-17",
            age_certificate: "18",
            director_id: "20",
        },
        {
            movie_name: "City of Men",
            movie_length: "140",
            movie_lang: "Portuguese",
            release_date: "2008-02-29",
            age_certificate: "15",
            director_id: "22",
        },
        {
            movie_name: "Cold Fish",
            movie_length: "108",
            movie_lang: "Japanese",
            release_date: "2010-09-12",
            age_certificate: "18",
            director_id: "30",
        },
        {
            movie_name: "Crouching Tiger Hidden Dragon",
            movie_length: "139",
            movie_lang: "Chinese",
            release_date: "2000-07-06",
            age_certificate: "12",
            director_id: "15",
        },
        {
            movie_name: "Eyes Wide Shut",
            movie_length: "130",
            movie_lang: "English",
            release_date: "1999-07-16",
            age_certificate: "18",
            director_id: "13",
        },
        {
            movie_name: "Forrest Gump",
            movie_length: "119",
            movie_lang: "English",
            release_date: "1994-07-06",
            age_certificate: "PG",
            director_id: "36",
        },
        {
            movie_name: "Gladiator",
            movie_length: "165",
            movie_lang: "English",
            release_date: "2000-05-05",
            age_certificate: "15",
            director_id: "27",
        },
        {
            movie_name: "Gone with the Wind",
            movie_length: "123",
            movie_lang: "English",
            release_date: "1939-12-15",
            age_certificate: "PG",
            director_id: "8",
        },
        {
            movie_name: "Goodfellas",
            movie_length: "148",
            movie_lang: "English",
            release_date: "1990-09-19",
            age_certificate: "15",
            director_id: "26",
        },
        {
            movie_name: "Grand Budapest Hotel",
            movie_length: "117",
            movie_lang: "English",
            release_date: "2014-07-03",
            age_certificate: "PG",
            director_id: "3",
        },
        {
            movie_name: "House of Flying Daggers",
            movie_length: "134",
            movie_lang: "Chinese",
            release_date: "2004-03-12",
            age_certificate: "12",
            director_id: "37",
        },
        {
            movie_name: "In the Mood for Love",
            movie_length: "124",
            movie_lang: "Chinese",
            release_date: "2001-02-02",
            age_certificate: "12",
            director_id: "35",
        },
        {
            movie_name: "Jaws",
            movie_length: "134",
            movie_lang: "English",
            release_date: "1975-06-20",
            age_certificate: "12",
            director_id: "31",
        },
        {
            movie_name: "Leon",
            movie_length: "123",
            movie_lang: "English",
            release_date: "1994-11-18",
            age_certificate: "15",
            director_id: "5",
        },
        {
            movie_name: "Let the Right One In",
            movie_length: "128",
            movie_lang: "Swedish",
            release_date: "2008-10-24",
            age_certificate: "15",
            director_id: "1",
        },
        {
            movie_name: "Life of Brian",
            movie_length: "126",
            movie_lang: "English",
            release_date: "1979-08-17",
            age_certificate: "15",
            director_id: "12",
        },
        {
            movie_name: "Life of Pi",
            movie_length: "129",
            movie_lang: "English",
            release_date: "2012-11-21",
            age_certificate: "PG",
            director_id: "15",
        },
        {
            movie_name: "Mary Poppins",
            movie_length: "87",
            movie_lang: "English",
            release_date: "1964-08-29",
            age_certificate: "U",
            director_id: "32",
        },
        {
            movie_name: "Never Let Me Go",
            movie_length: "117",
            movie_lang: "English",
            release_date: "2010-09-15",
            age_certificate: "15",
            director_id: "25",
        },
        {
            movie_name: "Oldboy",
            movie_length: "130",
            movie_lang: "Korean",
            release_date: "2005-03-25",
            age_certificate: "18",
            director_id: "23",
        },
        {
            movie_name: "Pans Labyrinth",
            movie_length: "98",
            movie_lang: "Spanish",
            release_date: "2006-12-29",
            age_certificate: "PG",
            director_id: "7",
        },
        {
            movie_name: "Ponyo",
            movie_length: "107",
            movie_lang: "Japanese",
            release_date: "2009-08-14",
            age_certificate: "U",
            director_id: "21",
        },
        {
            movie_name: "Pulp Fiction",
            movie_length: "136",
            movie_lang: "English",
            release_date: "1994-10-14",
            age_certificate: "15",
            director_id: "33",
        },
        {
            movie_name: "Raging Bull",
            movie_length: "132",
            movie_lang: "English",
            release_date: "1980-11-14",
            age_certificate: "18",
            director_id: "26",
        },
        {
            movie_name: "Rushmore",
            movie_length: "104",
            movie_lang: "English",
            release_date: "1998-11-12",
            age_certificate: "12",
            director_id: "3",
        },
        {
            movie_name: "Spider-Man",
            movie_length: "118",
            movie_lang: "English",
            release_date: "2002-05-03",
            age_certificate: "PG",
            director_id: "24",
        },
        {
            movie_name: "Spider-Man 2",
            movie_length: "115",
            movie_lang: "English",
            release_date: "2004-06-30",
            age_certificate: "PG",
            director_id: "24",
        },
        {
            movie_name: "Spider-Man 3",
            movie_length: "112",
            movie_lang: "English",
            release_date: "2007-05-04",
            age_certificate: "PG",
            director_id: "24",
        },
        {
            movie_name: "Spirited Away",
            movie_length: "120",
            movie_lang: "Japanese",
            release_date: "2001-06-19",
            age_certificate: "U",
            director_id: "21",
        },
        {
            movie_name: "Star Wars: A New Hope",
            movie_length: "123",
            movie_lang: "English",
            release_date: "1977-05-25",
            age_certificate: "PG",
            director_id: "17",
        },
        {
            movie_name: "Star Wars: Empire Strikes Back",
            movie_length: "150",
            movie_lang: "English",
            release_date: "1980-05-21",
            age_certificate: "PG",
            director_id: "17",
        },
        {
            movie_name: "Star Wars: Return of the Jedi",
            movie_length: "139",
            movie_lang: "English",
            release_date: "1983-05-25",
            age_certificate: "PG",
            director_id: "17",
        },
        {
            movie_name: "Submarine",
            movie_length: "115",
            movie_lang: "English",
            release_date: "2011-06-03",
            age_certificate: "15",
            director_id: "4",
        },
        {
            movie_name: "Taxi Driver",
            movie_length: "117",
            movie_lang: "English",
            release_date: "1976-02-7",
            age_certificate: "15",
            director_id: "26",
        },
        {
            movie_name: "The Darjeeling Limited",
            movie_length: "119",
            movie_lang: "English",
            release_date: "2007-09-29",
            age_certificate: "PG",
            director_id: "3",
        },
        {
            movie_name: "The Fifth Element",
            movie_length: "149",
            movie_lang: "English",
            release_date: "1997-05-09",
            age_certificate: "12",
            director_id: "5",
        },
        {
            movie_name: "The Lives of Others",
            movie_length: "165",
            movie_lang: "German",
            release_date: "2007-02-09",
            age_certificate: "15",
            director_id: "11",
        },
        {
            movie_name: "The Shining",
            movie_length: "126",
            movie_lang: "English",
            release_date: "1980-05-23",
            age_certificate: "18",
            director_id: "13",
        },
        {
            movie_name: "The Sound of Music",
            movie_length: "91",
            movie_lang: "English",
            release_date: "1965-03-02",
            age_certificate: "U",
            director_id: "34",
        },
        {
            movie_name: "The Wizard of Oz",
            movie_length: "120",
            movie_lang: "English",
            release_date: "1939-08-25",
            age_certificate: "U",
            director_id: "8",
        },
        {
            movie_name: "There Will Be Blood",
            movie_length: "168",
            movie_lang: "English",
            release_date: "2007-12-26",
            age_certificate: "15",
            director_id: "2",
        },
        {
            movie_name: "Three Billboards Outside Ebbing, Missouri ",
            movie_length: "134",
            movie_lang: "English",
            release_date: "2017-11-10",
            age_certificate: "15",
            director_id: "18",
        },
        {
            movie_name: "Titanic",
            movie_length: "143",
            movie_lang: "English",
            release_date: "1997-12-19",
            age_certificate: "12",
            director_id: "6",
        },
        {
            movie_name: "Top Gun",
            movie_length: "121",
            movie_lang: "English",
            release_date: "1986-05-16",
            age_certificate: "12",
            director_id: "28",
        },
        {
            movie_name: "Toy Story",
            movie_length: "95",
            movie_lang: "English",
            release_date: "1995-11-22",
            age_certificate: "U",
            director_id: "14",
        },
        {
            movie_name: "V for Vendetta",
            movie_length: "140",
            movie_lang: "English",
            release_date: "2006-03-17",
            age_certificate: "12",
            director_id: "19",
        },
        {
            movie_name: "Watchmen",
            movie_length: "138",
            movie_lang: "English",
            release_date: "2009-03-06",
            age_certificate: "12",
            director_id: "29",
        },
        {
            movie_name: "Way of the Dragon ",
            movie_length: "99",
            movie_lang: "Chinese",
            release_date: "1972-06-01",
            age_certificate: "12",
            director_id: "16",
        },
    ])
}
