/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AgcamachoAllinoneAuthV1 {
        "apiUrl": string;
        "createNewPasswordPath": string;
        "createUserPath": string;
        "createUserRedirectPath": string;
        "formDescriptionCreateAccount": string;
        "formDescriptionLogIn": string;
        "formDescriptionResetPassword": string;
        "formHeaderDescriptionIsSet": boolean;
        "formHeaderIsSet": boolean;
        "formTitleCreateAccount": string;
        "formTitleLogIn": string;
        "formTitleResetPassword": string;
        "loginPath": string;
        "loginRedirectPath": string;
        "resetPasswordPath": string;
    }
    interface AgcamachoApiKeyForm {
    }
}
declare global {
    interface HTMLAgcamachoAllinoneAuthV1Element extends Components.AgcamachoAllinoneAuthV1, HTMLStencilElement {
    }
    var HTMLAgcamachoAllinoneAuthV1Element: {
        prototype: HTMLAgcamachoAllinoneAuthV1Element;
        new (): HTMLAgcamachoAllinoneAuthV1Element;
    };
    interface HTMLAgcamachoApiKeyFormElement extends Components.AgcamachoApiKeyForm, HTMLStencilElement {
    }
    var HTMLAgcamachoApiKeyFormElement: {
        prototype: HTMLAgcamachoApiKeyFormElement;
        new (): HTMLAgcamachoApiKeyFormElement;
    };
    interface HTMLElementTagNameMap {
        "agcamacho-allinone-auth-v1": HTMLAgcamachoAllinoneAuthV1Element;
        "agcamacho-api-key-form": HTMLAgcamachoApiKeyFormElement;
    }
}
declare namespace LocalJSX {
    interface AgcamachoAllinoneAuthV1 {
        "apiUrl": string;
        "createNewPasswordPath": string;
        "createUserPath": string;
        "createUserRedirectPath": string;
        "formDescriptionCreateAccount"?: string;
        "formDescriptionLogIn"?: string;
        "formDescriptionResetPassword"?: string;
        "formHeaderDescriptionIsSet"?: boolean;
        "formHeaderIsSet"?: boolean;
        "formTitleCreateAccount"?: string;
        "formTitleLogIn"?: string;
        "formTitleResetPassword"?: string;
        "loginPath": string;
        "loginRedirectPath": string;
        "resetPasswordPath": string;
    }
    interface AgcamachoApiKeyForm {
    }
    interface IntrinsicElements {
        "agcamacho-allinone-auth-v1": AgcamachoAllinoneAuthV1;
        "agcamacho-api-key-form": AgcamachoApiKeyForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "agcamacho-allinone-auth-v1": LocalJSX.AgcamachoAllinoneAuthV1 & JSXBase.HTMLAttributes<HTMLAgcamachoAllinoneAuthV1Element>;
            "agcamacho-api-key-form": LocalJSX.AgcamachoApiKeyForm & JSXBase.HTMLAttributes<HTMLAgcamachoApiKeyFormElement>;
        }
    }
}
